@host = http://localhost
@port = 5114

@RestaurantsAPI_HostAddress = {{host}}:{{port}}

POST {{RestaurantsAPI_HostAddress}}/api/weatherforecast/generate?count=3
Content-Type: application/json

{
  "min": -1,
  "max": 98
}

###

