@host = http://localhost
@port = 5114

@RestaurantsAPI_HostAddress = {{host}}:{{port}}

GET {{RestaurantsAPI_HostAddress}}/api/weatherforecast/23/example?max=15
Accept: application/json
PojectUrl: {{RestaurantsAPI_HostAddress}}
Guid: {{$guid}}
LocalDate: {{$localDatetime iso8601}}
Randon-int: {{$randomInt}}

###

GET {{RestaurantsAPI_HostAddress}}/api/weatherforecast/currentDay
Accept: application/json
PojectUrl: {{RestaurantsAPI_HostAddress}}
Guid: {{$guid}}
LocalDate: {{$localDatetime iso8601}}
Randon-int: {{$randomInt}}

###

POST {{RestaurantsAPI_HostAddress}}/api/weatherforecast
Content-Type: application/json

"CloudGod"

###
